#!/bin/bash

brew install neovim tmux zsh stow starship fzf gnu-sed asimov lazygit ripgrep gh lazygit

brew tap homebrew/cask-fonts &&

git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
$(brew --prefix)/opt/fzf/install

git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm #ctrl+a I to install tmux plugins

curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash

export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm

nvm install --lts
nvm use --lts
npm i -g prettier eslint_d

