#!/bin/bash

brew install neovim tmux zsh stow fzf gnu-sed asimov lazygit ripgrep gh lazygit bat

brew tap homebrew/cask-fonts &&

$(brew --prefix)/opt/fzf/install

git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm #ctrl+a I to install tmux plugins

curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash

export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm

nvm install --lts
nvm use --lts
npm i -g prettier eslint_d

bash -c "$(curl --fail --show-error --silent --location https://raw.githubusercontent.com/zdharma-continuum/zinit/HEAD/scripts/install.sh)"
