#!/bin/bash

brew install --cask karabiner-elements
brew install neovim tmux nvm zsh stow starship fzf gnu-sed asimov lazygit
brew tap homebrew/cask-fonts
brew install --cask font-hack-nerd-font
sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
$(brew --prefix)/opt/fzf/install

