[[mgr.prepend_keymap]]
on   = [ "q" ]
run  = "quit --no-cwd-file"
desc = "Quit without changing directory"

[[mgr.prepend_keymap]]
on   = [ "Q" ]
run  = "quit"
desc = "Quit and change directory"

[[mgr.prepend_keymap]]
on   = [ "<Enter>" ]
run = "plugin --sync smart-enter"
desc = "Enter the child directory, or open the file"

[[mgr.prepend_keymap]]
on   = [ "o" ]
run = "plugin --sync smart-enter"
desc = "Enter the child directory, or open the file"
