[[manager.prepend_keymap]]
on   = [ "<Enter>" ]
run = "plugin --sync smart-enter"
desc = "Enter the child directory, or open the file"

[[manager.prepend_keymap]]
on   = [ "o" ]
run = "plugin --sync smart-enter"
desc = "Enter the child directory, or open the file"

[[manager.prepend_keymap]]
on   = [ "g", "?" ]
run = "help"
desc = "Open the help menu"
