#!/bin/bash
set -e

echo "Backup failed on $(date)" > ~/.backup-status
rsync -av --delete /home/mthorning/ pi:/backupdrive/home/mthorning/ \
    --exclude .cache/ \
    --exclude .local/share/Trash/
echo "Backup succeeded on $(date)" > ~/.backup-status
