#!/bin/bash

# Prints current volume.
#### dependencies:
# 2) alsamix --> audio infos


vol=$(amixer get Master | egrep "^  Mono"| cut -d"[" -f 2 | cut -d"%" -f 1)
icon="high"
[ "$vol" -le 66 ] && [ "$vol" -gt 33 ] && icon="medium"
[ "$vol" -le 33 ] && icon="low"
[ "$vol" -eq 0 ] && icon="mute"

display=$(echo $icon | sed "s/high/🔊/;s/medium/🔉/;s/low/🔈/;s/mute/🔇/")
printf "%s%s%%\n" "$display" "$vol"
